version: '3.1'
services:

  db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password --port 4306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "4306:4306"
    volumes:
      - db:/var/lib/mysql

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/PhotoVisor
      - gems:/usr/local/bundle:delegated
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    environment:
      DATABASE_USERNAME: 'root'
      DATABASE_PORT: '4306'
      DATABASE_HOST: 'db'
      DATABASE_PASSWORD: ''
    depends_on:
      - db
    
volumes:
  db:
  gems: